#!/bin/sh

DAEMON=aesdsocket

case "$1" in
    start)
        echo "Starting $DAEMON"
        start-stop-daemon -S -n $DAEMON -a /usr/bin/$DAEMON -- -d
	;;
    stop)
        echo "Stopping $DAEMON"
        start-stop-daemon server -K -n $DAEMON
        ;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

# Local Variables:
# mode: shell-script
# sh-basic-offset: 4
# indent-tabs-mode: nil
# sh-shell: sh
# End:
